/** Public shared infrastructure entry point for API modules. */
export { createDatabase, installDatabase } from './database.js';
export type {
  Database,
  DatabaseOptions,
  DatabaseTransaction,
  CategoryTable,
  ProductTable,
  ProductVariantTable,
  ModifierGroupTable,
  ModifierTable,
  ProductComboGroupTable,
  ProductComboItemTable,
  LocationPriceOverrideTable,
  AvailabilityRuleTable,
  AreaTable,
  DiningTableTable,
  SectionTable,
  TableSectionTable,
  RoleTable,
  StaffTable,
  TerminalPinAttemptTable,
  TerminalTable,
  VisitTable,
  AccountTable,
  OrderTable,
  OrderLineTable,
  PaymentTable,
} from './database.js';
